
# Site settings
title: FAF front page
# email: your-email@domain.com
description: >
  Facem ceva cu tolk.
baseurl: ""		# no trailing slash
url: ""	# no trailing slash
excerpt_separator: <!--more—->

about: >
  TODO
#twitter_username:    TODO
#github_username:     TODO
#facebook_username:   TODO
#linkedin_username:   TODO
#google_username:     TODO
#youtube_username:    TODO
#instagram_username:  TODO
#reddit_username:     TODO
#tumblr_username:     TODO
#lastfm_username:  	 TODO
#soundcloud_username: TODO
#miiverse_username:   TODO

# Build settings
markdown: kramdown

kramdown:
  input: GFM
